
class all_label (object):

    def __init__(self):
        self.all_label_dict = {
                  "Speech": 0,
                  "Male speech, man speaking": 0,
                  "Female speech, woman speaking": 0,
                  "Child speech, kid speaking": 0,
                  "Conversation": 0,
                  "Narration, monologue": 0,
                  "Babbling": 0,
                  "Speech synthesizer": 0,
                  "Shout": 0,
                  "Bellow": 0,
                  "Whoop": 0,
                  "Yell": 0,
                  "Battle cry": 0,
                  "Children shouting": 0,
                  "Screaming": 0,
                  "Whispering": 0,
                  "Laughter": 0,
                  "Baby laughter": 0,
                  "Giggle": 0,
                  "Snicker": 0,
                  "Belly laugh": 0,
                  "Chuckle, chortle": 0,
                  "Crying, sobbing": 0,
                  "Baby cry, infant cry": 0,
                  "Whimper": 0,
                  "Wail, moan": 0,
                  "Sigh": 0,
                  "Singing": 0,
                  "Choir": 0,
                  "Yodeling": 0,
                  "Chant": 0,
                  "Mantra": 0,
                  "Male singing": 0,
                  "Female singing": 0,
                  "Child singing": 0,
                  "Synthetic singing": 0,
                  "Rapping": 0,
                  "Humming": 0,
                  "Groan": 0,
                  "Grunt": 0,
                  "Whistling": 0,
                  "Breathing": 0,
                  "Wheeze": 0,
                  "Snoring": 0,
                  "Gasp": 0,
                  "Pant": 0,
                  "Snort": 0,
                  "Cough": 0,
                  "Throat clearing": 0,
                  "Sneeze": 0,
                  "Sniff": 0,
                  "Run": 0,
                  "Shuffle": 0,
                  "Walk, footsteps": 0,
                  "Chewing, mastication": 0,
                  "Biting": 0,
                  "Gargling": 0,
                  "Stomach rumble": 0,
                  "Burping, eructation": 0,
                  "Hiccup": 0,
                  "Fart": 0,
                  "Hands": 0,
                  "Finger snapping": 0,
                  "Clapping": 0,
                  "Heart sounds, heartbeat": 0,
                  "Heart murmur": 0,
                  "Cheering": 0,
                  "Applause": 0,
                  "Chatter": 0,
                  "Crowd": 0,
                  "Hubbub, speech noise, speech babble": 0,
                  "Children playing": 0,
                  "Animal": 0,
                  "Domestic animals, pets": 0,
                  "Dog": 0,
                  "Bark": 0,
                  "Yip": 0,
                  "Howl": 0,
                  "Bow-wow": 0,
                  "Growling": 0,
                  "Whimper (dog)": 0,
                  "Cat": 0,
                  "Purr": 0,
                  "Meow": 0,
                  "Hiss": 0,
                  "Caterwaul": 0,
                  "Livestock, farm animals, working animals": 0,
                  "Horse": 0,
                  "Clip-clop": 0,
                  "Neigh, whinny": 0,
                  "Cattle, bovinae": 0,
                  "Moo": 0,
                  "Cowbell": 0,
                  "Pig": 0,
                  "Oink": 0,
                  "Goat": 0,
                  "Bleat": 0,
                  "Sheep": 0,
                  "Fowl": 0,
                  "Chicken, rooster": 0,
                  "Cluck": 0,
                  "Crowing, cock-a-doodle-doo": 0,
                  "Turkey": 0,
                  "Gobble": 0,
                  "Duck": 0,
                  "Quack": 0,
                  "Goose": 0,
                  "Honk": 0,
                  "Wild animals": 0,
                  "Roaring cats (lions, tigers)": 0,
                  "Roar": 0,
                  "Bird": 0,
                  "Bird vocalization, bird call, bird song": 0,
                  "Chirp, tweet": 0,
                  "Squawk": 0,
                  "Pigeon, dove": 0,
                  "Coo": 0,
                  "Crow": 0,
                  "Caw": 0,
                  "Owl": 0,
                  "Hoot": 0,
                  "Bird flight, flapping wings": 0,
                  "Canidae, dogs, wolves": 0,
                  "Rodents, rats, mice": 0,
                  "Mouse": 0,
                  "Patter": 0,
                  "Insect": 0,
                  "Cricket": 0,
                  "Mosquito": 0,
                  "Fly, housefly": 0,
                  "Buzz": 0,
                  "Bee, wasp, etc.": 0,
                  "Frog": 0,
                  "Croak": 0,
                  "Snake": 0,
                  "Rattle": 0,
                  "Whale vocalization": 0,
                  "Music": 0,
                  "Musical instrument": 0,
                  "Plucked string instrument": 0,
                  "Guitar": 0,
                  "Electric guitar": 0,
                  "Bass guitar": 0,
                  "Acoustic guitar": 0,
                  "Steel guitar, slide guitar": 0,
                  "Tapping (guitar technique)": 0,
                  "Strum": 0,
                  "Banjo": 0,
                  "Sitar": 0,
                  "Mandolin": 0,
                  "Zither": 0,
                  "Ukulele": 0,
                  "Keyboard (musical)": 0,
                  "Piano": 0,
                  "Electric piano": 0,
                  "Organ": 0,
                  "Electronic organ": 0,
                  "Hammond organ": 0,
                  "Synthesizer": 0,
                  "Sampler": 0,
                  "Harpsichord": 0,
                  "Percussion": 0,
                  "Drum kit": 0,
                  "Drum machine": 0,
                  "Drum": 0,
                  "Snare drum": 0,
                  "Rimshot": 0,
                  "Drum roll": 0,
                  "Bass drum": 0,
                  "Timpani": 0,
                  "Tabla": 0,
                  "Cymbal": 0,
                  "Hi-hat": 0,
                  "Wood block": 0,
                  "Tambourine": 0,
                  "Rattle (instrument)": 0,
                  "Maraca": 0,
                  "Gong": 0,
                  "Tubular bells": 0,
                  "Mallet percussion": 0,
                  "Marimba, xylophone": 0,
                  "Glockenspiel": 0,
                  "Vibraphone": 0,
                  "Steelpan": 0,
                  "Orchestra": 0,
                  "Brass instrument": 0,
                  "French horn": 0,
                  "Trumpet": 0,
                  "Trombone": 0,
                  "Bowed string instrument": 0,
                  "String section": 0,
                  "Violin, fiddle": 0,
                  "Pizzicato": 0,
                  "Cello": 0,
                  "Double bass": 0,
                  "Wind instrument, woodwind instrument": 0,
                  "Flute": 0,
                  "Saxophone": 0,
                  "Clarinet": 0,
                  "Harp": 0,
                  "Bell": 0,
                  "Church bell": 0,
                  "Jingle bell": 0,
                  "Bicycle bell": 0,
                  "Tuning fork": 0,
                  "Chime": 0,
                  "Wind chime": 0,
                  "Change ringing (campanology)": 0,
                  "Harmonica": 0,
                  "Accordion": 0,
                  "Bagpipes": 0,
                  "Didgeridoo": 0,
                  "Shofar": 0,
                  "Theremin": 0,
                  "Singing bowl": 0,
                  "Scratching (performance technique)": 0,
                  "Pop music": 0,
                  "Hip hop music": 0,
                  "Beatboxing": 0,
                  "Rock music": 0,
                  "Heavy metal": 0,
                  "Punk rock": 0,
                  "Grunge": 0,
                  "Progressive rock": 0,
                  "Rock and roll": 0,
                  "Psychedelic rock": 0,
                  "Rhythm and blues": 0,
                  "Soul music": 0,
                  "Reggae": 0,
                  "Country": 0,
                  "Swing music": 0,
                  "Bluegrass": 0,
                  "Funk": 0,
                  "Folk music": 0,
                  "Middle Eastern music": 0,
                  "Jazz": 0,
                  "Disco": 0,
                  "Classical music": 0,
                  "Opera": 0,
                  "Electronic music": 0,
                  "House music": 0,
                  "Techno": 0,
                  "Dubstep": 0,
                  "Drum and bass": 0,
                  "Electronica": 0,
                  "Electronic dance music": 0,
                  "Ambient music": 0,
                  "Trance music": 0,
                  "Music of Latin America": 0,
                  "Salsa music": 0,
                  "Flamenco": 0,
                  "Blues": 0,
                  "Music for children": 0,
                  "New-age music": 0,
                  "Vocal music": 0,
                  "A capella": 0,
                  "Music of Africa": 0,
                  "Afrobeat": 0,
                  "Christian music": 0,
                  "Gospel music": 0,
                  "Music of Asia": 0,
                  "Carnatic music": 0,
                  "Music of Bollywood": 0,
                  "Ska": 0,
                  "Traditional music": 0,
                  "Independent music": 0,
                  "Song": 0,
                  "Background music": 0,
                  "Theme music": 0,
                  "Jingle (music)": 0,
                  "Soundtrack music": 0,
                  "Lullaby": 0,
                  "Video game music": 0,
                  "Christmas music": 0,
                  "Dance music": 0,
                  "Wedding music": 0,
                  "Happy music": 0,
                  "Funny music": 0,
                  "Sad music": 0,
                  "Tender music": 0,
                  "Exciting music": 0,
                  "Angry music": 0,
                  "Scary music": 0,
                  "Wind": 0,
                  "Rustling leaves": 0,
                  "Wind noise (microphone)": 0,
                  "Thunderstorm": 0,
                  "Thunder": 0,
                  "Water": 0,
                  "Rain": 0,
                  "Raindrop": 0,
                  "Rain on surface": 0,
                  "Stream": 0,
                  "Waterfall": 0,
                  "Ocean": 0,
                  "Waves, surf": 0,
                  "Steam": 0,
                  "Gurgling": 0,
                  "Fire": 0,
                  "Crackle": 0,
                  "Vehicle": 0,
                  "Boat, Water vehicle": 0,
                  "Sailboat, sailing ship": 0,
                  "Rowboat, canoe, kayak": 0,
                  "Motorboat, speedboat": 0,
                  "Ship": 0,
                  "Motor vehicle (road)": 0,
                  "Car": 0,
                  "Vehicle horn, car horn, honking": 0,
                  "Toot": 0,
                  "Car alarm": 0,
                  "Power windows, electric windows": 0,
                  "Skidding": 0,
                  "Tire squeal": 0,
                  "Car passing by": 0,
                  "Race car, auto racing": 0,
                  "Truck": 0,
                  "Air brake": 0,
                  "Air horn, truck horn": 0,
                  "Reversing beeps": 0,
                  "Ice cream truck, ice cream van": 0,
                  "Bus": 0,
                  "Emergency vehicle": 0,
                  "Police car (siren)": 0,
                  "Ambulance (siren)": 0,
                  "Fire engine, fire truck (siren)": 0,
                  "Motorcycle": 0,
                  "Traffic noise, roadway noise": 0,
                  "Rail transport": 0,
                  "Train": 0,
                  "Train whistle": 0,
                  "Train horn": 0,
                  "Railroad car, train wagon": 0,
                  "Train wheels squealing": 0,
                  "Subway, metro, underground": 0,
                  "Aircraft": 0,
                  "Aircraft engine": 0,
                  "Jet engine": 0,
                  "Propeller, airscrew": 0,
                  "Helicopter": 0,
                  "Fixed-wing aircraft, airplane": 0,
                  "Bicycle": 0,
                  "Skateboard": 0,
                  "Engine": 0,
                  "Light engine (high frequency)": 0,
                  "Dental drill, dentist's drill": 0,
                  "Lawn mower": 0,
                  "Chainsaw": 0,
                  "Medium engine (mid frequency)": 0,
                  "Heavy engine (low frequency)": 0,
                  "Engine knocking": 0,
                  "Engine starting": 0,
                  "Idling": 0,
                  "Accelerating, revving, vroom": 0,
                  "Door": 0,
                  "Doorbell": 0,
                  "Ding-dong": 0,
                  "Sliding door": 0,
                  "Slam": 0,
                  "Knock": 0,
                  "Tap": 0,
                  "Squeak": 0,
                  "Cupboard open or close": 0,
                  "Drawer open or close": 0,
                  "Dishes, pots, and pans": 0,
                  "Cutlery, silverware": 0,
                  "Chopping (food)": 0,
                  "Frying (food)": 0,
                  "Microwave oven": 0,
                  "Blender": 0,
                  "Water tap, faucet": 0,
                  "Sink (filling or washing)": 0,
                  "Bathtub (filling or washing)": 0,
                  "Hair dryer": 0,
                  "Toilet flush": 0,
                  "Toothbrush": 0,
                  "Electric toothbrush": 0,
                  "Vacuum cleaner": 0,
                  "Zipper (clothing)": 0,
                  "Keys jangling": 0,
                  "Coin (dropping)": 0,
                  "Scissors": 0,
                  "Electric shaver, electric razor": 0,
                  "Shuffling cards": 0,
                  "Typing": 0,
                  "Typewriter": 0,
                  "Computer keyboard": 0,
                  "Writing": 0,
                  "Alarm": 0,
                  "Telephone": 0,
                  "Telephone bell ringing": 0,
                  "Ringtone": 0,
                  "Telephone dialing, DTMF": 0,
                  "Dial tone": 0,
                  "Busy signal": 0,
                  "Alarm clock": 0,
                  "Siren": 0,
                  "Civil defense siren": 0,
                  "Buzzer": 0,
                  "Smoke detector, smoke alarm": 0,
                  "Fire alarm": 0,
                  "Foghorn": 0,
                  "Whistle": 0,
                  "Steam whistle": 0,
                  "Mechanisms": 0,
                  "Ratchet, pawl": 0,
                  "Clock": 0,
                  "Tick": 0,
                  "Tick-tock": 0,
                  "Gears": 0,
                  "Pulleys": 0,
                  "Sewing machine": 0,
                  "Mechanical fan": 0,
                  "Air conditioning": 0,
                  "Cash register": 0,
                  "Printer": 0,
                  "Camera": 0,
                  "Single-lens reflex camera": 0,
                  "Tools": 0,
                  "Hammer": 0,
                  "Jackhammer": 0,
                  "Sawing": 0,
                  "Filing (rasp)": 0,
                  "Sanding": 0,
                  "Power tool": 0,
                  "Drill": 0,
                  "Explosion": 0,
                  "Gunshot, gunfire": 0,
                  "Machine gun": 0,
                  "Fusillade": 0,
                  "Artillery fire": 0,
                  "Cap gun": 0,
                  "Fireworks": 0,
                  "Firecracker": 0,
                  "Burst, pop": 0,
                  "Eruption": 0,
                  "Boom": 0,
                  "Wood": 0,
                  "Chop": 0,
                  "Splinter": 0,
                  "Crack": 0,
                  "Glass": 0,
                  "Chink, clink": 0,
                  "Shatter": 0,
                  "Liquid": 0,
                  "Splash, splatter": 0,
                  "Slosh": 0,
                  "Squish": 0,
                  "Drip": 0,
                  "Pour": 0,
                  "Trickle, dribble": 0,
                  "Gush": 0,
                  "Fill (with liquid)": 0,
                  "Spray": 0,
                  "Pump (liquid)": 0,
                  "Stir": 0,
                  "Boiling": 0,
                  "Sonar": 0,
                  "Arrow": 0,
                  "Whoosh, swoosh, swish": 0,
                  "Thump, thud": 0,
                  "Thunk": 0,
                  "Electronic tuner": 0,
                  "Effects unit": 0,
                  "Chorus effect": 0,
                  "Basketball bounce": 0,
                  "Bang": 0,
                  "Slap, smack": 0,
                  "Whack, thwack": 0,
                  "Smash, crash": 0,
                  "Breaking": 0,
                  "Bouncing": 0,
                  "Whip": 0,
                  "Flap": 0,
                  "Scratch": 0,
                  "Scrape": 0,
                  "Rub": 0,
                  "Roll": 0,
                  "Crushing": 0,
                  "Crumpling, crinkling": 0,
                  "Tearing": 0,
                  "Beep, bleep": 0,
                  "Ping": 0,
                  "Ding": 0,
                  "Clang": 0,
                  "Squeal": 0,
                  "Creak": 0,
                  "Rustle": 0,
                  "Whir": 0,
                  "Clatter": 0,
                  "Sizzle": 0,
                  "Clicking": 0,
                  "Clickety-clack": 0,
                  "Rumble": 0,
                  "Plop": 0,
                  "Jingle, tinkle": 0,
                  "Hum": 0,
                  "Zing": 0,
                  "Boing": 0,
                  "Crunch": 0,
                  "Silence": 0,
                  "Sine wave": 0,
                  "Harmonic": 0,
                  "Chirp tone": 0,
                  "Sound effect": 0,
                  "Pulse": 0,
                  "Inside, small room": 0,
                  "Inside, large room or hall": 0,
                  "Inside, public space": 0,
                  "Outside, urban or manmade": 0,
                  "Outside, rural or natural": 0,
                  "Reverberation": 0,
                  "Echo": 0,
                  "Noise": 0,
                  "Environmental noise": 0,
                  "Static": 0,
                  "Mains hum": 0,
                  "Distortion": 0,
                  "Sidetone": 0,
                  "Cacophony": 0,
                  "White noise": 0,
                  "Pink noise": 0,
                  "Throbbing": 0,
                  "Vibration": 0,
                  "Television": 0,
                  "Radio": 0,
                  "Field recording": 0
                  }

        self.l2_label_list = [
                  "Shout",
                  "Bellow",
                  "Whoop",
                  "Yell",
                  "Battle cry",
                  "Children shouting",
                  "Screaming",
                  "Crying, sobbing",
                  "Wail, moan",
                  "Cheering",
                  "Crowd",
                  "Run",
                  "Applause",
                  "Hubbub, speech noise, speech babble",
                  "Baby cry, infant cry",
                  "Cough",
                  "Thunderstorm",
                  "Thunder",
                  "Crackle",
                  "Dental drill, dentist's drill",
                  "Smoke detector, smoke alarm",
                  "Fire alarm",
                  "Foghorn",
                  "Alarm",
                  "Alarm clock",
                  "Siren",
                  "Mechanisms",
                  "Civil defense siren",
                  "Buzzer",
                  "Hammer",
                  "Jackhammer",
                  "Power tool",
                  "Drill",
                  "Burst, pop",
                  "Crack",
                  "Car alarm",
                  "Vehicle horn, car horn, honking",
                  "Skidding",
                  "Toot",
                  "Race car, auto racing",
                  "Tire squeal",
                  "Air brake",
                  "Air horn, truck horn",
                  "Traffic noise, roadway noise",
                  "Reversing beeps",
                  "Emergency vehicle",
                  "Police car (siren)",
                  "Ambulance (siren)",
                  "Fire engine, fire truck (siren)",
                  "Engine knocking",
                  "Engine starting",
                  "Breaking",
                  "Bouncing",
                  "Scratch",
                  "Thump, thud",
                  "Bang",
                  "Slam",
                  "Knock",
                  "Tap",
                  "Basketball bounce"
                  ] 

        self.l3_label_list = [
                  "Explosion",
                  "Gunshot, gunfire",
                  "Machine gun",
                  "Fusillade",
                  "Artillery fire",
                  "Cap gun",
                  "Eruption",
                  "Fire",
                  "Fireworks",
                  "Firecracker"
                  ]          
